#!/usr/bin/env bash
# Runs the Go backend and Vite frontend together. The frontend's own scripts
# call `bunx vite`/`bunx vitest`/etc. instead of the `.bin` shims directly —
# on WSL2, a node_modules generated by Windows-side bun has Windows-shaped
# .bin shims that Linux's bash can't execute through the /mnt/c mount. bunx
# resolves each package's JS entry point directly, sidestepping that shim
# entirely, so this works the same on Windows, WSL2, and Linux.
set -em  # -m: job control, so each `&` job gets its own process group to kill as a whole

pids=()
cleanup() {
  trap - SIGINT SIGTERM EXIT
  for pid in "${pids[@]}"; do
    kill -- "-$pid" 2>/dev/null || true
  done
}
trap cleanup SIGINT SIGTERM EXIT

bun run backend &
pids+=("$!")
bun run frontend &
pids+=("$!")

wait
